#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f $PROXY $1 > $3; cd -
}

URL="https://download.owncloud.com/server/stable/owncloud-complete-20230906.zip"

dl $URL /usr/local/src owncloud.zip
