#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f $PROXY $1 > $3; cd -
}

VER="10.0.2"
URL="https://download.owncloud.org/community/owncloud-${VER}.zip"

dl $URL /usr/local/src owncloud-$VER.zip
