#!/bin/bash
set -Eeuo pipefail

image=owncloud/server@sha256:dbebc24fe77a35c5de621d38a3f7264ffb43e3ee321928cde9a563a72b8ff366
archive=/usr/local/src/owncloud-server.tar
local_tag=owncloud/server:11.0.0-turnkey-dbebc24fe77a

if [[ -n ${FAB_HTTP_PROXY:-} ]]; then
    export HTTP_PROXY=$FAB_HTTP_PROXY
    export HTTPS_PROXY=$FAB_HTTP_PROXY
fi

skopeo copy --override-os linux --override-arch amd64 \
    "docker://docker.io/$image" "docker-archive:$archive:$local_tag"

cat > /usr/local/src/owncloud-image-source <<EOF
source=docker.io/owncloud/server
version=11.0.0
digest=sha256:dbebc24fe77a35c5de621d38a3f7264ffb43e3ee321928cde9a563a72b8ff366
local_tag=$local_tag
EOF
