#!/bin/bash -e

DB_NAME=owncloud
DB_USER=owncloud
DB_PASS=$(mcookie)
REDIS_PASS=$(mcookie)

# configure apache
a2dissite 000-default
a2ensite owncloud.conf
a2enmod rewrite
a2enmod headers
a2enmod proxy
a2enmod proxy_http

# start services
service mysql start
service apache2 start

# setup the database
mysqladmin create $DB_NAME
mysql --batch --execute "CREATE USER '$DB_USER'@'172.28.0.%' IDENTIFIED BY '$DB_PASS'; GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'172.28.0.%'; FLUSH PRIVILEGES;"

install -d -m 700 /etc/owncloud
install -d -m 700 /var/lib/owncloud
install -m 600 /usr/local/src/owncloud-image-source /etc/owncloud/image-source

cat > /etc/owncloud/image.conf <<EOF
OWNCLOUD_IMAGE=owncloud/server:11.0.0-turnkey-dbebc24fe77a
OWNCLOUD_VERSION=11.0.0
OWNCLOUD_DIGEST=sha256:dbebc24fe77a35c5de621d38a3f7264ffb43e3ee321928cde9a563a72b8ff366
EOF

cat > /etc/owncloud/owncloud.env <<EOF
OWNCLOUD_DOMAIN=localhost
OWNCLOUD_TRUSTED_DOMAINS=localhost,127.0.0.1
OWNCLOUD_OVERWRITE_CLI_URL=https://localhost
OWNCLOUD_OVERWRITE_PROTOCOL=https
OWNCLOUD_DB_TYPE=mysql
OWNCLOUD_DB_NAME=$DB_NAME
OWNCLOUD_DB_USERNAME=$DB_USER
OWNCLOUD_DB_PASSWORD=$DB_PASS
OWNCLOUD_DB_HOST=172.28.0.1
OWNCLOUD_MYSQL_UTF8MB4=true
OWNCLOUD_REDIS_ENABLED=true
OWNCLOUD_REDIS_HOST=172.28.0.1
OWNCLOUD_REDIS_PORT=6379
OWNCLOUD_REDIS_PASSWORD=$REDIS_PASS
OWNCLOUD_ADMIN_USERNAME=admin
OWNCLOUD_ADMIN_PASSWORD=turnkey
EOF
chmod 600 /etc/owncloud/image.conf /etc/owncloud/owncloud.env

cat > /etc/mysql/mariadb.conf.d/60-owncloud.cnf <<'EOF'
[mariadbd]
bind-address = 172.28.0.1
EOF

sed -i 's/^bind .*/bind 172.28.0.1/' /etc/redis/redis.conf
sed -i "s/^# requirepass .*/requirepass $REDIS_PASS/" /etc/redis/redis.conf

# stop services
service mysql stop
service apache2 stop

systemctl enable docker.service
install -d /etc/systemd/system/multi-user.target.wants
ln -s ../owncloud-network.service \
    /etc/systemd/system/multi-user.target.wants/owncloud-network.service
ln -s ../owncloud.service \
    /etc/systemd/system/multi-user.target.wants/owncloud.service
