#!/bin/bash -ex

DB_NAME=owncloud
DB_USER=owncloud
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey

WEBROOT=/var/www/owncloud
DATAROOT=${WEBROOT}-data
CONF=$WEBROOT/config/config.php

# unpack tarball to webroot and set permissions
unzip /usr/local/src/owncloud*.zip -d $(dirname $WEBROOT)
[[ ! -d "$WEBROOT" ]] && exit 1
rm -rf /usr/local/src/owncloud*
mkdir -p $DATAROOT

# tweak footer
TEMPLATE=$WEBROOT/core/templates/layout.guest.php
sed -i "s|<footer>.*|<footer><p class='info' style='width: auto \!important;'><a href='https://www.turnkeylinux.org/owncloud'>ownCloud Appliance</a> \&ndash; Powered by <a href='https://www.turnkeylinux.org'>TurnKey Linux</a></p></footer>|" $TEMPLATE

# configure apache
a2dissite 000-default
a2ensite owncloud.conf
a2enmod rewrite
a2enmod headers
a2enmod env
a2enmod dir
a2enmod mime

# start services
service mysql start
service apache2 start

# setup the database
mysqladmin create $DB_NAME
mysql --batch --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# command-line install
chown -R www-data:www-data $WEBROOT
cd $WEBROOT
php occ maintenance:install --database "mysql" \
    --database-name "$DB_NAME"  --database-user "$DB_USER" --database-pass "$DB_PASS" \
    --admin-user "$ADMIN_NAME" --admin-pass "$ADMIN_PASS" \
    --data-dir "$DATAROOT"

# enable notify owncloud that we are using cron
mysql --batch --database=$DB_NAME --execute "INSERT INTO oc_appconfig (appid, configkey, configvalue) VALUES ('core', 'backgroundjobs_mode', 'cron');"

# adjust owncloud config for redis
sed -i '/^);/d' $CONF
cat >> $CONF <<EOF
  'memcache.local' => '\OC\Memcache\Redis',
  'redis' => [
      'host' => '/var/run/redis/redis.sock',
      'port' => 0,
  ],
  'memcache.locking' => '\OC\Memcache\Redis',
);
EOF

# add www-data user to redis group
usermod -a -G redis www-data

# adjust redis config
sed -i 's|# unixsocket .*|unixsocket /var/run/redis/redis.sock|g' /etc/redis/redis.conf
sed -i 's|# unixsocketperm .*|unixsocketperm 770|g' /etc/redis/redis.conf

chown -R www-data:www-data $WEBROOT $DATAROOT

# stop services
service mysql stop
service apache2 stop
